includes/Database/QuestionResponseFactory.php, includes/Database/SurveyInstanceFactory.php, includes/Database/TeamInstanceFactory.php, survey_on_me.cls.php, survey_on_me.php, survey_results.cls.php, survey_results.php
Added instructor view of survey results on an individual.
=> Added instructor view of survey results on an individual.

css/style.css, dashboard.cls.php, includes/Database/SurveyInstanceFactory.php, survey_on_me.cls.php
Implemented students view of the survey results.
=> Implemented students view of the survey results.

css/style.css, register.php
Removed defaults from input fields.
=> Removed defaults from input fields.

css/style.css, responses.cls.php, responses.php, survey_on_me.cls.php, survey_on_me.php, survey_results.cls.php
Added actual responses to responses.php file.
=> Added actual responses to responses.php file.

dashboard.cls.php, dashboard.php, includes/Database/SurveyFactory.php, post_survey.php
Implemented giving a launched instance a new survey name.
=> Implemented giving a launched instance a new survey name.

dashboard.cls.php, dashboard.php, edit_survey.php, includes/Database/SurveyFactory.php
Finished implementing survey edit.
=> Finished implementing survey edit.

includes/Database/SurveyFactory.php, includes/Database/SurveyQuestionFactory.php
Saves survey's name in edit survey page.
=> Saves survey's name in edit survey page.

includes/ToneAnalyzer/tone.inc.php
=> test comment in tone

dashboard.cls.php, dashboard.php
The instructir's dashboard table was split into an Instances table, and
a Templates table.
=> Split the instructors surveys dashboard into seperate tables.

dashboard.cls.php, dashboard.php, edit_team.php, includes/Database/QuestionFactory.php, includes/Database/SurveyFactory.php, includes/Database/SurveyInstanceFactory.php, includes/Database/TeamFactory.php, includes/Database/TeamInstanceFactory.php, includes/Database/TeamUserFactory.php, post_survey.cls.php, survey_results.cls.php
Teams are now duplicated when a survey is launched.
=> Fix bug 21

responses.php, survey_on_me.php, take_survey.php
Removed duplicate session statements.
=> Removed duplicate session statements.

includes/Database/UserFactory.php, includes/functions.inc.php
=> Added password encryption.

dashboard.php, edit_team.php, includes/Database/TeamFactory.php, includes/Database/TeamUserFactory.php
Added proper editing of teams and team membership.
=> Team edit work

dashboard.php, edit_survey.php, includes/Database/SurveyFactory.php
Added deleting of survey questions.
=> Added deleting of survey questions.

responses.cls.php
Added survey question back into responses page.  Also removed unused
function.
=> Added survey question back into responses page.

includes/ToneAnalyzer/tone.inc.php, responses.cls.php, survey_on_me.cls.php, survey_on_me.php
tone to survey summary cleanned up
=> Tone2surveyonme

logout.php, register.php
Added header and nav bar and link to css to logout.php
added back link next to link Register.php to index.php(login page)
=> Styled Logout and added back link on Register pages

survey_on_me.cls.php
I messed up the orginal loop when I added tone checker to surevey_on_me
(summary view). answers to the same question should now be grouped.
=> corrected the question user loop on survey_on_me.cls.php

css/style.css, js/piechart.js, survey_on_me.php, survey_results.cls.php, survey_results.php
=> Survey results work.

css/style.css, dashboard.php, edit_survey.php, edit_team.php, index.php, post_survey.php, register.php, responses.php, review_results.php, survey_on_me.php, survey_results.php, take_survey.php
=> CrossYourFingers

css/style.css, survey_on_me.cls.php, survey_on_me.php
put buttons for Tone UI in survey_on_me.php inside loop to show only
when the reviewer was the logged in person.
=> Survey_on_me.php Tone UI now only shows for instructor and viewer who is reviewer

post_survey.php
Date fields have a required attribute, and they now allow cancelling
when date fields are empty.
=> Allow cancelling when date fields are empty.

js/register.js, register.php
Added field validation of register page.
=> Added field validation of register page.

css/style.css
=> CSS change with z-index: 1; within .fixedheader

css/style.css, includes/ToneAnalyzer/tone.inc.php, responses.cls.php, responses.php, survey_on_me.php
Reformated the tone results into 3 tables. Changed the CSS based on what
we talked about today for caps and alignment. Also added hide/show for
tone ui
=> Tone Result Table format, CSS changes and hide/show Tone

survey_results.cls.php, survey_results.php
Moved the display of the graph to the opposite side of the page.
=> Moved the display of the graph to the opposite side of the page.

css/style.css
Updated CSS after Dave's change to include CSS for tone results bar
chart
=> Changed CSS for Tone Summary Barchart

edit_survey.php
=> Commit to master King616

dashboard.cls.php, dashboard.php, includes/Database/QuestionResponseFactory.php, includes/Database/SurveyCompleteFactory.php, includes/Database/SurveyFactory.php, responses.cls.php, responses.php
Implemented having student redo survey.
=> Implemented having student redo survey.

css/style.css
Added hatched background for unsubmitted fields.
=> Added hatched background for unsubmitted fields.

css/style.css, take_survey.cls.php
Adjusted footer so it stays at bottom and fixed buttons on take
survey.php
=> Changes to Footer and Buttons

take_survey.cls.php
=> Submit Change

includes/footer.php
Added &copy for copyright and added verbiage
=> Footer Copyright

responses.cls.php
Added: If no submissions are present, we hide Redo section, and disabled
tone buttons.
=> Added: If no submissions are present, we hide Redo section, and disabled tone buttons.

dashboard.cls.php
Added a table row which says None found for Surveys To Do and Surveys
Results on Me tables, if there are no surveys to be done or reviewed.
=> Added a table row which says None found.

index.php
Removed default user name of belgort.
=> Removed default user name of belgort.

includes/Database/UserFactory.php, includes/functions.inc.php, js/register.js, register.php
Changed validation of registration inputs.
=> Changed validation of registration inputs.

edit_survey.php, responses.cls.php, survey_on_me.cls.php
Removed hard coded rows and cols from textarea elements.
=> Removed hard coded rows and cols from textarea elements.

take_survey.cls.php
Changed font size to 13.33px to match the other buttons
=> Button Fix

css/style.css, responses.cls.php
Change the background to the not submitted background for when a survey
was submitted, but an answer was left blank.
=> Made more obvious when response has not been entered.

dashboard.cls.php
Fixed indexing of reviewees to redo surveys.
=> Fixed indexing of reviewees to redo surveys.

css/style.css, take_survey.cls.php, take_survey.php
=> Changes Text box and Take Survey

css/style.css
=> NoResponse CSS changes

take_survey.cls.php
=> Correct buttons

css/style.css, includes/footer.php, responses.cls.php, responses.php
Fixed HTML errors, but no functional change to page.
=> Fixed HTML errors.

responses.cls.php
Made textarea on Responses page readOnly.
=> Made textarea on Responses page readOnly.
